In [1]:
# Import libraries required for creating models and validating them
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from time import time
from sklearn import metrics as mt
from IPython.html import widgets 
import warnings
warnings.filterwarnings('ignore')

/Users/pankaj/anaconda/envs/ML7331/lib/python3.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [2]:
#Read the data
ccdefault=pd.read_csv('./UCI_Credit_Card.csv')

In [3]:
#rename the columns to clearer names
ccdefault.rename(columns={'default.payment.next.month':'DEFAULT'},inplace=True)
ccdefault.rename(columns={'PAY_0':'PAY_1'},inplace=True)

In [4]:
#Cleaning of data
cc = ccdefault.copy() # taking a copy in memory
if 'DEFAULT' in cc:
    y = cc['DEFAULT'].values
    del cc['DEFAULT']
    del cc['BILL_AMT1']
    del cc['BILL_AMT2']
    del cc['BILL_AMT3']
    del cc['BILL_AMT4']
    del cc['BILL_AMT5']
    del cc['BILL_AMT6']
    X = cc.values
num_cv_iterations = 5
num_instances = len(y)
cv_object = StratifiedShuffleSplit(n_splits = num_cv_iterations,
test_size = 0.20, train_size = 0.80, random_state=10)
cv_object.get_n_splits(X, y)
print(cv_object)
for train_index, test_index in cv_object.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

StratifiedShuffleSplit(n_splits=5, random_state=10, test_size=0.2,
            train_size=0.8)
TRAIN: [26296   633  2863 ... 15141 19066  7166] TEST: [ 5469 17052 23411 ... 24675 28588 16031]
TRAIN: [17006  5992 28816 ... 10798 22887 23796] TEST: [  683 10937   999 ...   875  4336  2721]
TRAIN: [ 5957 25994 14047 ...    53   805 24297] TEST: [14399 23807  6988 ...  9804 17546 23927]
TRAIN: [11516  8559 14297 ... 14603 13364    89] TEST: [13759 19809 18958 ... 27816 11181 16164]
TRAIN: [ 2233 17193  9866 ... 12371  9657 11083] TEST: [28935 15053 22533 ... 22298  4357 23349]


In [5]:
#Scale the data so the distance metric is not affected by the range of explanatory variables
scl_obj = StandardScaler()
scl_obj.fit(X_train) 

X_train_scaled = scl_obj.transform(X_train) # apply to training
X_test_scaled = scl_obj.transform(X_test) # apply those means and std to the test set (without snooping at the test set values)

In [6]:
#Need to collect max accuracy 
max_acc = 0

In [7]:
parameters = [10, 20, 50, 100]
for K in parameters:
    print("For k = ", K, "and metric = Euclidean: ")
    knn = KNeighborsClassifier(n_neighbors=K, weights='uniform', metric='euclidean')
    knn.fit(X_train_scaled,y_train)
    y_hat = knn.predict(X_test_scaled)
    acc = mt.accuracy_score(y_test,y_hat)
    conf = mt.confusion_matrix(y_test,y_hat)
    print('accuracy:', acc )
    print(conf)
    ClassReport = mt.classification_report(y_test,y_hat)
    print(ClassReport)
    max_acc = (acc) if acc>max_acc else (max_acc)
    
print(max_acc)    

For k =  10 and metric = Euclidean: 
accuracy: 0.8065
[[4466  207]
 [ 954  373]]
              precision    recall  f1-score   support

           0       0.82      0.96      0.88      4673
           1       0.64      0.28      0.39      1327

    accuracy                           0.81      6000
   macro avg       0.73      0.62      0.64      6000
weighted avg       0.78      0.81      0.78      6000

For k =  20 and metric = Euclidean: 
accuracy: 0.8101666666666667
[[4456  217]
 [ 922  405]]
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      4673
           1       0.65      0.31      0.42      1327

    accuracy                           0.81      6000
   macro avg       0.74      0.63      0.65      6000
weighted avg       0.79      0.81      0.78      6000

For k =  50 and metric = Euclidean: 
accuracy: 0.8111666666666667
[[4479  194]
 [ 939  388]]
              precision    recall  f1-score   support

           0       0.83 

In [89]:
parameters = [10, 20, 50, 100]
for K in parameters:
    print("For k = ", K, "and metric = Cosine: ")
    knn = KNeighborsClassifier(n_neighbors=K, weights='uniform', metric='cosine')
    knn.fit(X_train_scaled,y_train)
    y_hat = knn.predict(X_test_scaled)
    acc = mt.accuracy_score(y_test,y_hat)
    conf = mt.confusion_matrix(y_test,y_hat)
    print('accuracy:', acc )
    print(conf )
    ClassReport = mt.classification_report(y_test,y_hat)
    print(ClassReport)
    max_acc = (acc) if acc>max_acc else (max_acc)
    
print(max_acc)    

For k =  10 and metric = Cosine: 
accuracy: 0.8041666666666667
[[4437  236]
 [ 939  388]]
              precision    recall  f1-score   support

           0       0.83      0.95      0.88      4673
           1       0.62      0.29      0.40      1327

    accuracy                           0.80      6000
   macro avg       0.72      0.62      0.64      6000
weighted avg       0.78      0.80      0.78      6000

For k =  20 and metric = Cosine: 
accuracy: 0.8121666666666667
[[4435  238]
 [ 889  438]]
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      4673
           1       0.65      0.33      0.44      1327

    accuracy                           0.81      6000
   macro avg       0.74      0.64      0.66      6000
weighted avg       0.79      0.81      0.79      6000

For k =  50 and metric = Cosine: 
accuracy: 0.8113333333333334
[[4429  244]
 [ 888  439]]
              precision    recall  f1-score   support

           0       0.

In [90]:
parameters = [10, 20, 50, 100]
for K in parameters:
    print("For k = ", K, "and metric = Manhattan: ")
    knn = KNeighborsClassifier(n_neighbors=K, weights='uniform', metric='manhattan')
    knn.fit(X_train_scaled,y_train)
    y_hat = knn.predict(X_test_scaled)
    acc = mt.accuracy_score(y_test,y_hat)
    conf = mt.confusion_matrix(y_test,y_hat)
    print('accuracy:', acc )
    print(conf )
    ClassReport = mt.classification_report(y_test,y_hat)
    print(ClassReport)
    max_acc = (acc) if acc>max_acc else (max_acc)
    
print(max_acc)    

For k =  10 and metric = Manhattan: 
accuracy: 0.8026666666666666
[[4457  216]
 [ 968  359]]
              precision    recall  f1-score   support

           0       0.82      0.95      0.88      4673
           1       0.62      0.27      0.38      1327

    accuracy                           0.80      6000
   macro avg       0.72      0.61      0.63      6000
weighted avg       0.78      0.80      0.77      6000

For k =  20 and metric = Manhattan: 
accuracy: 0.8078333333333333
[[4466  207]
 [ 946  381]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      4673
           1       0.65      0.29      0.40      1327

    accuracy                           0.81      6000
   macro avg       0.74      0.62      0.64      6000
weighted avg       0.79      0.81      0.78      6000

For k =  50 and metric = Manhattan: 
accuracy: 0.8103333333333333
[[4488  185]
 [ 953  374]]
              precision    recall  f1-score   support

           0