In [73]:
# Import libraries required for creating models and validating them
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from time import time
from sklearn import metrics as mt
from IPython.html import widgets 
import warnings
warnings.filterwarnings('ignore')

In [74]:
#Read the data
ccdefault=pd.read_csv('./UCI_Credit_Card.csv')

In [75]:
#rename the columns to clearer names
ccdefault.rename(columns={'default.payment.next.month':'DEFAULT'},inplace=True)
ccdefault.rename(columns={'PAY_0':'PAY_1'},inplace=True)

In [76]:
#Cleaning of data
cc = ccdefault.copy() # taking a copy in memory
if 'DEFAULT' in cc:
    y = cc['DEFAULT'].values
    del cc['DEFAULT']
    del cc['BILL_AMT1']
    del cc['BILL_AMT2']
    del cc['BILL_AMT3']
    del cc['BILL_AMT4']
    del cc['BILL_AMT5']
    del cc['BILL_AMT6']
    X = cc.values
num_cv_iterations = 5
num_instances = len(y)
cv_object = StratifiedShuffleSplit(n_splits = num_cv_iterations,
test_size = 0.20, train_size = 0.80, random_state=10)
cv_object.get_n_splits(X, y)
print(cv_object)
for train_index, test_index in cv_object.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

StratifiedShuffleSplit(n_splits=5, random_state=10, test_size=0.2,
            train_size=0.8)
TRAIN: [26296   633  2863 ... 15141 19066  7166] TEST: [ 5469 17052 23411 ... 24675 28588 16031]
TRAIN: [17006  5992 28816 ... 10798 22887 23796] TEST: [  683 10937   999 ...   875  4336  2721]
TRAIN: [ 5957 25994 14047 ...    53   805 24297] TEST: [14399 23807  6988 ...  9804 17546 23927]
TRAIN: [11516  8559 14297 ... 14603 13364    89] TEST: [13759 19809 18958 ... 27816 11181 16164]
TRAIN: [ 2233 17193  9866 ... 12371  9657 11083] TEST: [28935 15053 22533 ... 22298  4357 23349]


In [77]:
#Scale the data so the distance metric is not affected by the range of explanatory variables
scl_obj = StandardScaler()
scl_obj.fit(X_train) 

X_train_scaled = scl_obj.transform(X_train) # apply to training
X_test_scaled = scl_obj.transform(X_test) # apply those means and std to the test set (without snooping at the test set values)

In [ ]:
#Need to collect max accuracy 
max_acc = 0

In [91]:
parameters = [10, 20, 50, 100]
for train_indices, test_indices in cv_object.split(X,y): 
    X_train_scaled = X[train_indices]
    y_train = y[train_indices]
    
    X_test_scaled = X[test_indices]
    y_test = y[test_indices]   
    for K in parameters:
        print("For k = ", K, "and metric = Euclidean: ")
        knn = KNeighborsClassifier(n_neighbors=K, weights='uniform', metric='euclidean')
        knn.fit(X_train_scaled,y_train)
        y_hat = knn.predict(X_test_scaled)
        acc = mt.accuracy_score(y_test,y_hat)
        conf = mt.confusion_matrix(y_test,y_hat)
        print('accuracy:', acc )
        print(conf)
        ClassReport = mt.classification_report(y_test,y_hat)
        print(ClassReport)
        max_acc = (acc) if acc>max_acc else (max_acc)
    
print("Max accuracy is:", max_acc)   

For k =  10 and metric = Euclidean: 
accuracy: 0.7726666666666666
[[4568  105]
 [1259   68]]
              precision    recall  f1-score   support

           0       0.78      0.98      0.87      4673
           1       0.39      0.05      0.09      1327

    accuracy                           0.77      6000
   macro avg       0.59      0.51      0.48      6000
weighted avg       0.70      0.77      0.70      6000

For k =  20 and metric = Euclidean: 
accuracy: 0.777
[[4627   46]
 [1292   35]]
              precision    recall  f1-score   support

           0       0.78      0.99      0.87      4673
           1       0.43      0.03      0.05      1327

    accuracy                           0.78      6000
   macro avg       0.61      0.51      0.46      6000
weighted avg       0.70      0.78      0.69      6000

For k =  50 and metric = Euclidean: 
accuracy: 0.781
[[4663   10]
 [1304   23]]
              precision    recall  f1-score   support

           0       0.78      1.00     

In [92]:
parameters = [10, 20, 50, 100]
for train_indices, test_indices in cv_object.split(X,y): 
    X_train_scaled = X[train_indices]
    y_train = y[train_indices]
    
    X_test_scaled = X[test_indices]
    y_test = y[test_indices] 
    for K in parameters:
        print("For k = ", K, "and metric = Cosine: ")
        knn = KNeighborsClassifier(n_neighbors=K, weights='uniform', metric='cosine')
        knn.fit(X_train_scaled,y_train)
        y_hat = knn.predict(X_test_scaled)
        acc = mt.accuracy_score(y_test,y_hat)
        conf = mt.confusion_matrix(y_test,y_hat)
        print('accuracy:', acc )
        print(conf )
        ClassReport = mt.classification_report(y_test,y_hat)
        print(ClassReport)
        max_acc = (acc) if acc>max_acc else (max_acc)
    
print("Max accuracy is:", max_acc)    

For k =  10 and metric = Cosine: 
accuracy: 0.7758333333333334
[[4571  102]
 [1243   84]]
              precision    recall  f1-score   support

           0       0.79      0.98      0.87      4673
           1       0.45      0.06      0.11      1327

    accuracy                           0.78      6000
   macro avg       0.62      0.52      0.49      6000
weighted avg       0.71      0.78      0.70      6000

For k =  20 and metric = Cosine: 
accuracy: 0.777
[[4618   55]
 [1283   44]]
              precision    recall  f1-score   support

           0       0.78      0.99      0.87      4673
           1       0.44      0.03      0.06      1327

    accuracy                           0.78      6000
   macro avg       0.61      0.51      0.47      6000
weighted avg       0.71      0.78      0.69      6000

For k =  50 and metric = Cosine: 
accuracy: 0.7788333333333334
[[4660   13]
 [1314   13]]
              precision    recall  f1-score   support

           0       0.78      1.00 

In [93]:
parameters = [10, 20, 50, 100]
for train_indices, test_indices in cv_object.split(X,y): 
    X_train_scaled = X[train_indices]
    y_train = y[train_indices]
    
    X_test_scaled = X[test_indices]
    y_test = y[test_indices] 
    for K in parameters:
        print("For k = ", K, "and metric = Manhattan: ")
        knn = KNeighborsClassifier(n_neighbors=K, weights='uniform', metric='manhattan')
        knn.fit(X_train_scaled,y_train)
        y_hat = knn.predict(X_test_scaled)
        acc = mt.accuracy_score(y_test,y_hat)
        conf = mt.confusion_matrix(y_test,y_hat)
        print('accuracy:', acc )
        print(conf )
        ClassReport = mt.classification_report(y_test,y_hat)
        print(ClassReport)
        max_acc = (acc) if acc>max_acc else (max_acc)
    
print("Max accuracy is:", max_acc)    

For k =  10 and metric = Manhattan: 
accuracy: 0.777
[[4565  108]
 [1230   97]]
              precision    recall  f1-score   support

           0       0.79      0.98      0.87      4673
           1       0.47      0.07      0.13      1327

    accuracy                           0.78      6000
   macro avg       0.63      0.52      0.50      6000
weighted avg       0.72      0.78      0.71      6000

For k =  20 and metric = Manhattan: 
accuracy: 0.7773333333333333
[[4608   65]
 [1271   56]]
              precision    recall  f1-score   support

           0       0.78      0.99      0.87      4673
           1       0.46      0.04      0.08      1327

    accuracy                           0.78      6000
   macro avg       0.62      0.51      0.48      6000
weighted avg       0.71      0.78      0.70      6000

For k =  50 and metric = Manhattan: 
accuracy: 0.779
[[4648   25]
 [1301   26]]
              precision    recall  f1-score   support

           0       0.78      0.99     